COMMON_SYNONYMS: dict[str, set[str]] = {
    "title": {"name", "headline", "label", "product_name", "item_name"},
    "price": {"cost", "amount", "unit_price", "sale_price", "price_amount", "regular_price"},
    "sku": {"sku", "barcode", "upc", "ean", "isbn", "code"},
    "inventory_quantity": {"stock", "quantity", "inventory", "qty", "stock_level", "available_quantity"},
    "description": {"desc", "body_html", "body", "summary", "details", "description_html"},
    "image": {"images", "photo", "picture", "media", "thumbnail", "image_url", "featured_image"},
    "email": {"e_mail", "mail", "email_address", "contact_email"},
    "phone": {"telephone", "phone_number", "tel", "mobile", "cell"},
    "first_name": {"firstname", "given_name", "forename", "fname"},
    "last_name": {"lastname", "surname", "family_name", "lname"},
    "address": {"addresses", "location", "shipping_address", "billing_address"},
    "tags": {"tag", "labels", "categories", "collections", "category_ids"},
    "handle": {"slug", "url_handle", "permalink", "custom_url"},
    "external_id": {"id", "source_id", "origin_id", "remote_id", "legacy_id"},
    "vendor": {"brand", "manufacturer", "supplier", "seller"},
    "product_type": {"type", "category", "product_category", "item_type"},
    "total": {"total_price", "order_total", "grand_total", "total_amount"},
    "subtotal": {"subtotal_price", "sub_total", "subtotal_amount"},
    "currency": {"currency_code", "currency_iso", "monetary_currency"},
    "notes": {"note", "comment", "customer_note", "internal_note"},
    "status": {"state", "order_status", "fulfillment_status", "shipping_status"},
    "weight": {"mass", "weight_grams", "weight_ounces"},
}
