from datetime import datetime, UTC
from typing import Dict, Any
from pydantic import Field
from app.shared.kernel.entity import Entity

class PromptHistory(Entity[str]):
    """Domain representation of a specific prompt-response interaction with an LLM."""
    runtimeId: str = Field(..., description="ID of the parent AIRuntimeLog")
    provider: str = Field(..., description="LLM provider name (e.g. openai, claude, gemini)")
    context: str = Field(..., description="Context of the prompt")
    model: str = Field(..., description="Model identifier used (e.g. gpt-4o)")
    system_prompt: str = Field(..., description="System instructions sent to the model")
    user_prompt: str = Field(..., description="User prompt text")
    llm_response: str = Field(..., description="Text generated by the LLM")
    token_used: int = Field(..., description="Token used on this prompt")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
